"""The investigation tree as an evidence-backed graph.

Turns the RCA tree into a serialisable document where every node names the
evidence records that support it and the decisions that produced it. Possible
only because evidence ids are derived from content rather than generated by the
database - otherwise the rows would have to be inserted and read back before the
tree could reference them, which would drag this out of the pure layer.
"""

import hashlib
from dataclasses import replace
from typing import Any

from app.analysis.investigation.models import EvidenceRecord
from app.analysis.rca.models import DriverNode
from app.analysis.trace import DecisionRecord
from app.db.models.enums import EvidenceType


def node_key(node: DriverNode) -> str:
    """A short, opaque, DOM-safe handle for a node.

    ``node_id`` is built by joining ``dimension=value`` pairs from user data, so
    it can contain ``|``, ``=``, spaces and ``#`` and is unusable as a fragment
    identifier.

    Hashed with blake2b rather than ``hash()``: the built-in is salted per process
    for strings, so the same tree would get different keys on every run and an
    anchor link would break on reload.
    """
    digest = hashlib.blake2b(node.node_id.encode("utf-8"), digest_size=6).hexdigest()
    return f"d{node.depth}-{digest}"


def build(
    root: DriverNode | None,
    records: list[EvidenceRecord],
    decisions: tuple[DecisionRecord, ...] | list[DecisionRecord] = (),
) -> dict[str, Any] | None:
    """The tree as a plain document, with evidence and decision ids attached."""
    if root is None:
        return None

    by_node: dict[str, list[str]] = {}
    for record in records:
        if record.node_id:
            by_node.setdefault(record.node_id, []).append(str(record.id))

    # The synthetic root stands for the KPI as a whole, and its node_id is empty,
    # so no segment record points at it. The records that *do* describe the whole
    # movement are attached explicitly - otherwise the one node every reader looks
    # at first would be the only one with no evidence behind it.
    root_records = [
        str(record.id)
        for record in records
        if record.node_id is None
        and record.evidence_type
        in {
            EvidenceType.KPI_CHANGE,
            EvidenceType.COMPARISON,
            EvidenceType.RECONCILIATION,
        }
    ]
    by_node.setdefault(root.node_id, []).extend(root_records)

    decisions_by_node: dict[str, list[int]] = {}
    for decision in decisions:
        if decision.node_id:
            decisions_by_node.setdefault(decision.node_id, []).append(decision.sequence)

    def convert(node: DriverNode) -> dict[str, Any]:
        return {
            "node_id": node.node_id,
            "node_key": node_key(node),
            "depth": node.depth,
            # Same shape as DriverRead.path, so a consumer reading either the
            # findings payload or this tree never has to branch on it.
            "path": [{"dimension": d, "value": v} for d, v in node.path],
            "dimension": node.dimension,
            "value": node.value,
            "value_is_null": node.value_is_null,
            "current_value": node.current_value,
            "previous_value": node.previous_value,
            "absolute_change": node.absolute_change,
            "percent_change": node.percent_change,
            "percent_change_undefined_reason": node.percent_change_undefined_reason,
            "contribution": node.contribution,
            "contribution_basis": node.contribution_basis.value,
            "unattributable_reason": (
                node.unattributable_reason.value if node.unattributable_reason else None
            ),
            "share_of_parent_change": node.share_of_parent_change,
            "rate_effect": node.rate_effect,
            "mix_effect": node.mix_effect,
            "current_count": node.current_count,
            "previous_count": node.previous_count,
            "current_rows": node.current_rows,
            "previous_rows": node.previous_rows,
            "current_share": node.current_share,
            "previous_share": node.previous_share,
            "expected_change": node.expected_change,
            "excess_change": node.excess_change,
            "is_new_segment": node.is_new_segment,
            "is_lost_segment": node.is_lost_segment,
            "low_support": node.low_support,
            "support_reason": node.support_reason,
            "is_other_bucket": node.is_other_bucket,
            "is_pure_split": node.is_pure_split,
            "classification": node.classification.value,
            "rank": node.rank,
            "child_dimension": node.child_dimension,
            "child_split_type": node.child_split_type,
            "child_explanatory_power": node.child_explanatory_power,
            "unexplained_share": node.unexplained_share,
            "stop_reason": node.stop_reason,
            "evidence_ids": by_node.get(node.node_id, []),
            "decision_sequences": decisions_by_node.get(node.node_id, []),
            "children": [convert(child) for child in node.children],
        }

    return convert(root)


def stamp_decisions(
    decisions: list[DecisionRecord], records: list[EvidenceRecord]
) -> list[DecisionRecord]:
    """Attach the evidence ids for the node each decision was about.

    So a decision can be read alongside the numbers it was made on rather than
    only next to a node id.
    """
    by_node: dict[str, list[str]] = {}
    for record in records:
        if record.node_id:
            by_node.setdefault(record.node_id, []).append(str(record.id))

    return [
        replace(decision, evidence_ids=tuple(by_node.get(decision.node_id or "", ())))
        for decision in decisions
    ]
