"""Initial Phase 1 schema.

Hand-written rather than autogenerated so the JSON/JSONB variant is preserved:
autogenerate flattens ``JSON().with_variant(JSONB, "postgresql")`` to plain
JSON, which would silently drop JSONB on PostgreSQL.

Revision ID: 0001
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.models.base import JSONColumn
from app.db.models.enums import (
    Aggregation,
    ComparisonPeriod,
    DatasetStatus,
    FileFormat,
    SourceType,
    UploadStatus,
)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _in_list(column: str, enum: type) -> str:
    return f"{column} IN (" + ", ".join(f"'{m.value}'" for m in enum) + ")"


def upgrade() -> None:
    op.create_table(
        "companies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_companies"),
        sa.UniqueConstraint("slug", name="uq_companies_slug"),
    )

    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name="fk_users_company_id_companies", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_users"),
        sa.UniqueConstraint("company_id", "email", name="uq_users_company_email"),
    )
    op.create_index("ix_users_company_id", "users", ["company_id"])

    op.create_table(
        "sql_connections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("host", sa.String(255), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("database_name", sa.String(128), nullable=False),
        sa.Column("username", sa.String(128), nullable=False),
        # Fernet token. There is deliberately no plaintext password column.
        sa.Column("password_encrypted", sa.Text(), nullable=False),
        sa.Column("encrypt", sa.Boolean(), nullable=False),
        sa.Column("trust_server_certificate", sa.Boolean(), nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_test_ok", sa.Boolean(), nullable=True),
        sa.Column("last_test_error", sa.String(500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name="fk_sql_connections_company_id_companies",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_sql_connections_created_by_users", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_sql_connections"),
        sa.UniqueConstraint("company_id", "name", name="uq_sql_connections_company_name"),
    )
    op.create_index("ix_sql_connections_company_id", "sql_connections", ["company_id"])

    op.create_table(
        "datasets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(20), nullable=False),
        sa.Column("original_filename", sa.String(255), nullable=True),
        sa.Column("file_format", sa.String(20), nullable=False),
        sa.Column("storage_key", sa.String(512), nullable=True),
        sa.Column("normalized_key", sa.String(512), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum_sha256", sa.String(64), nullable=True),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("column_count", sa.Integer(), nullable=True),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("upload_status", sa.String(20), nullable=False),
        sa.Column("status", sa.String(30), nullable=False),
        sa.Column("quality_state", sa.String(10), nullable=True),
        sa.Column("ingest_options", JSONColumn, nullable=True),
        sa.Column("source_connection_id", sa.Uuid(), nullable=True),
        sa.Column("source_query", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("profiling_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("profiling_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(_in_list("source_type", SourceType), name="ck_datasets_source_type_valid"),
        sa.CheckConstraint(_in_list("file_format", FileFormat), name="ck_datasets_file_format_valid"),
        sa.CheckConstraint(_in_list("upload_status", UploadStatus), name="ck_datasets_upload_status_valid"),
        sa.CheckConstraint(_in_list("status", DatasetStatus), name="ck_datasets_status_valid"),
        sa.ForeignKeyConstraint(
            ["company_id"], ["companies.id"], name="fk_datasets_company_id_companies", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="fk_datasets_user_id_users", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"], ["sql_connections.id"],
            name="fk_datasets_source_connection_id_sql_connections", ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_datasets"),
    )
    op.create_index("ix_datasets_company_id", "datasets", ["company_id"])
    op.create_index("ix_datasets_company_created", "datasets", ["company_id", "created_at"])
    op.create_index("ix_datasets_company_status", "datasets", ["company_id", "status"])
    op.create_index("ix_datasets_company_checksum", "datasets", ["company_id", "checksum_sha256"])

    op.create_table(
        "dataset_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("profile_version", sa.Integer(), nullable=False),
        sa.Column("row_count", sa.BigInteger(), nullable=False),
        sa.Column("column_count", sa.Integer(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("duplicate_row_count", sa.BigInteger(), nullable=True),
        sa.Column("duplicate_row_pct", sa.Float(), nullable=True),
        sa.Column("duplicate_check_skipped", sa.Boolean(), nullable=False),
        sa.Column("missing_cell_count", sa.BigInteger(), nullable=False),
        sa.Column("missing_cell_pct", sa.Float(), nullable=False),
        sa.Column("quality_status", sa.String(20), nullable=True),
        sa.Column("engine", sa.String(20), nullable=False),
        sa.Column("exact_quantiles", sa.Boolean(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("extra", JSONColumn, nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name="fk_dataset_profiles_dataset_id_datasets",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_dataset_profiles"),
        sa.UniqueConstraint("dataset_id", name="uq_dataset_profiles_dataset_id"),
    )

    op.create_table(
        "column_profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_profile_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("column_name", sa.String(255), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("raw_type", sa.String(50), nullable=False),
        sa.Column("inferred_type", sa.String(20), nullable=False),
        sa.Column("semantic_type", sa.String(20), nullable=False),
        sa.Column("conversion_confidence", sa.Float(), nullable=True),
        sa.Column("requires_conversion", sa.Boolean(), nullable=False),
        sa.Column("invalid_value_count", sa.BigInteger(), nullable=False),
        sa.Column("sample_invalid_values", JSONColumn, nullable=True),
        sa.Column("null_count", sa.BigInteger(), nullable=False),
        sa.Column("null_pct", sa.Float(), nullable=False),
        sa.Column("unique_count", sa.BigInteger(), nullable=True),
        sa.Column("unique_pct", sa.Float(), nullable=True),
        sa.Column("min_value", sa.String(255), nullable=True),
        sa.Column("max_value", sa.String(255), nullable=True),
        sa.Column("mean", sa.Float(), nullable=True),
        sa.Column("median", sa.Float(), nullable=True),
        sa.Column("stddev", sa.Float(), nullable=True),
        sa.Column("outlier_count", sa.BigInteger(), nullable=True),
        sa.Column("outlier_lower", sa.Float(), nullable=True),
        sa.Column("outlier_upper", sa.Float(), nullable=True),
        sa.Column("percentiles", JSONColumn, nullable=True),
        sa.Column("top_values", JSONColumn, nullable=True),
        sa.Column("datetime_stats", JSONColumn, nullable=True),
        sa.Column("kpi_measure_score", sa.Float(), nullable=True),
        sa.Column("kpi_dimension_score", sa.Float(), nullable=True),
        sa.Column("kpi_time_score", sa.Float(), nullable=True),
        sa.Column("suggested_aggregation", sa.String(20), nullable=True),
        sa.Column("candidate_reasons", JSONColumn, nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_profile_id"], ["dataset_profiles.id"],
            name="fk_column_profiles_dataset_profile_id_dataset_profiles", ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name="fk_column_profiles_dataset_id_datasets",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_column_profiles"),
        sa.UniqueConstraint(
            "dataset_profile_id", "column_name", name="uq_column_profiles_profile_column"
        ),
    )
    op.create_index("ix_column_profiles_dataset_profile_id", "column_profiles", ["dataset_profile_id"])
    op.create_index("ix_column_profiles_dataset_id", "column_profiles", ["dataset_id"])
    op.create_index(
        "ix_column_profiles_dataset_semantic", "column_profiles", ["dataset_id", "semantic_type"]
    )

    op.create_table(
        "kpi_definitions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("column_name", sa.String(255), nullable=False),
        sa.Column("aggregation", sa.String(20), nullable=False),
        sa.Column("time_column", sa.String(255), nullable=True),
        sa.Column("dimensions", JSONColumn, nullable=False),
        sa.Column("comparison", sa.String(30), nullable=False),
        sa.Column("comparison_config", JSONColumn, nullable=True),
        sa.Column("filters", JSONColumn, nullable=True),
        sa.Column("definition", JSONColumn, nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("validation_state", sa.String(10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            _in_list("aggregation", Aggregation), name="ck_kpi_definitions_aggregation_valid"
        ),
        sa.CheckConstraint(
            _in_list("comparison", ComparisonPeriod), name="ck_kpi_definitions_comparison_valid"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name="fk_kpi_definitions_dataset_id_datasets",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="fk_kpi_definitions_created_by_users", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_kpi_definitions"),
    )
    op.create_index("ix_kpi_definitions_dataset_id", "kpi_definitions", ["dataset_id"])
    op.create_index("ix_kpi_definitions_company_id", "kpi_definitions", ["company_id"])
    op.create_index("ix_kpi_definitions_dataset_active", "kpi_definitions", ["dataset_id", "is_active"])
    # At most one active definition per dataset. Partial indexes are
    # PostgreSQL-only; the service enforces the same rule for other dialects.
    if op.get_bind().dialect.name == "postgresql":
        op.create_index(
            "uq_kpi_definitions_one_active",
            "kpi_definitions",
            ["dataset_id"],
            unique=True,
            postgresql_where=sa.text("is_active"),
        )

    op.create_table(
        "schema_validations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("kpi_definition_id", sa.Uuid(), nullable=True),
        sa.Column("mode", sa.String(20), nullable=False),
        sa.Column("state", sa.String(10), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("info_count", sa.Integer(), nullable=False),
        sa.Column("issues", JSONColumn, nullable=False),
        sa.Column("rules_version", sa.String(20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "state IN ('pass', 'warning', 'blocked')", name="ck_schema_validations_state_valid"
        ),
        sa.CheckConstraint(
            "mode IN ('structural', 'analysis')", name="ck_schema_validations_mode_valid"
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name="fk_schema_validations_dataset_id_datasets",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kpi_definition_id"], ["kpi_definitions.id"],
            name="fk_schema_validations_kpi_definition_id_kpi_definitions", ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_schema_validations"),
    )
    op.create_index("ix_schema_validations_dataset_id", "schema_validations", ["dataset_id"])
    op.create_index(
        "ix_schema_validations_dataset_created", "schema_validations", ["dataset_id", "created_at"]
    )


def downgrade() -> None:
    op.drop_table("schema_validations")
    op.drop_table("kpi_definitions")
    op.drop_table("column_profiles")
    op.drop_table("dataset_profiles")
    op.drop_table("datasets")
    op.drop_table("sql_connections")
    op.drop_table("users")
    op.drop_table("companies")
