"""Persisted investigations, structured evidence, query trace and audit trail.

Hand-written rather than autogenerated, for the reason 0001 gives: autogenerate
flattens ``JSON().with_variant(JSONB, "postgresql")`` to plain JSON, which would
silently drop JSONB on PostgreSQL.

Four tables rather than one. ``investigation_queries`` is separate because the
SQL text is the largest thing in the record and reading an investigation must not
drag it along; ``investigation_evidence`` is separate because evidence has to be
filtered, paged, and addressable by its own id.

Revision ID: 0003
Revises: 0002
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.db.models.base import JSONColumn
from app.db.models.enums import (
    AuditEventType,
    EvidenceConfidence,
    EvidenceQuality,
    EvidenceType,
    EvidenceValidationStatus,
    InvestigationStatus,
    QueryStatus,
    ReconciliationStatus,
    TreeDriftStatus,
)

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _in_list(column: str, enum: type) -> str:
    return f"{column} IN (" + ", ".join(f"'{m.value}'" for m in enum) + ")"


def upgrade() -> None:
    op.create_table(
        "investigations",
        sa.Column("id", sa.Uuid(), nullable=False),
        # Denormalised and un-FK'd, like kpi_definitions.company_id.
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("kpi_definition_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        # --- lifecycle
        sa.Column("question", sa.String(500), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("analysis_state", sa.String(30), nullable=True),
        # --- the plan
        sa.Column("kpi_name", sa.String(150), nullable=False),
        sa.Column("measure_column", sa.String(255), nullable=False),
        sa.Column("aggregation", sa.String(20), nullable=False),
        sa.Column("time_column", sa.String(255), nullable=True),
        sa.Column("comparison", sa.String(30), nullable=False),
        sa.Column("grain", sa.String(20), nullable=True),
        sa.Column("max_drivers", sa.Integer(), nullable=False),
        sa.Column("max_tree_depth", sa.Integer(), nullable=False),
        # --- the answer, typed. Windows are half-open: end is exclusive.
        sa.Column("previous_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_value", sa.Float(), nullable=True),
        sa.Column("current_value", sa.Float(), nullable=True),
        sa.Column("absolute_change", sa.Float(), nullable=True),
        sa.Column("percentage_change", sa.Float(), nullable=True),
        sa.Column("change_direction", sa.String(10), nullable=True),
        sa.Column("severity", sa.String(10), nullable=True),
        # --- execution metadata
        sa.Column("rows_scanned", sa.BigInteger(), nullable=False),
        sa.Column("rows_in_previous_period", sa.BigInteger(), nullable=False),
        sa.Column("rows_in_current_period", sa.BigInteger(), nullable=False),
        sa.Column("rows_outside_periods", sa.BigInteger(), nullable=False),
        sa.Column("queries_executed", sa.Integer(), nullable=False),
        sa.Column("execution_time_ms", sa.Integer(), nullable=False),
        # --- verdicts
        sa.Column("contribution_sum", sa.Float(), nullable=True),
        sa.Column("reconciliation_status", sa.String(20), nullable=True),
        sa.Column("reconciliation_tolerance", sa.Float(), nullable=True),
        sa.Column("tree_drift_status", sa.String(20), nullable=True),
        sa.Column("evidence_quality", sa.String(20), nullable=True),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        # --- payloads nothing filters inside
        sa.Column("result", JSONColumn, nullable=True),
        sa.Column("tree", JSONColumn, nullable=True),
        sa.Column("decisions", JSONColumn, nullable=True),
        sa.Column("quality_checks", JSONColumn, nullable=True),
        sa.Column("limitations", JSONColumn, nullable=True),
        sa.Column("notices", JSONColumn, nullable=True),
        # --- provenance and timing
        sa.Column("engine_version", sa.String(20), nullable=False),
        sa.Column("source_relation", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            _in_list("status", InvestigationStatus), name="ck_investigations_status_valid"
        ),
        sa.CheckConstraint(
            _in_list("reconciliation_status", ReconciliationStatus),
            name="ck_investigations_reconciliation_status_valid",
        ),
        sa.CheckConstraint(
            _in_list("tree_drift_status", TreeDriftStatus),
            name="ck_investigations_tree_drift_status_valid",
        ),
        sa.CheckConstraint(
            _in_list("evidence_quality", EvidenceQuality),
            name="ck_investigations_evidence_quality_valid",
        ),
        # CASCADE: an investigation whose underlying rows are gone can no longer
        # be verified against them, and keeping it would be misleading.
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name="fk_investigations_dataset_id_datasets",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["kpi_definition_id"],
            ["kpi_definitions.id"],
            name="fk_investigations_kpi_definition_id_kpi_definitions",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name="fk_investigations_created_by_users",
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_investigations"),
    )
    op.create_index("ix_investigations_company_id", "investigations", ["company_id"])
    op.create_index("ix_investigations_dataset_id", "investigations", ["dataset_id"])
    op.create_index(
        "ix_investigations_company_created", "investigations", ["company_id", "created_at"]
    )
    op.create_index(
        "ix_investigations_dataset_created", "investigations", ["dataset_id", "created_at"]
    )
    op.create_index("ix_investigations_company_status", "investigations", ["company_id", "status"])

    op.create_table(
        "investigation_evidence",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        # Denormalised so GET /api/evidence/{id} is one indexed read.
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("evidence_type", sa.String(30), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("metric", sa.String(150), nullable=True),
        sa.Column("dimension", sa.String(255), nullable=True),
        sa.Column("dimension_value", sa.String(500), nullable=True),
        sa.Column("dimension_value_is_null", sa.Boolean(), nullable=False),
        sa.Column("previous_period", sa.String(100), nullable=True),
        sa.Column("current_period", sa.String(100), nullable=True),
        sa.Column("previous_value", sa.Float(), nullable=True),
        sa.Column("current_value", sa.Float(), nullable=True),
        sa.Column("absolute_change", sa.Float(), nullable=True),
        sa.Column("percentage_change", sa.Float(), nullable=True),
        sa.Column("contribution_percentage", sa.Float(), nullable=True),
        # Its own column: explainability is not a share and may exceed 100%.
        sa.Column("explanatory_power", sa.Float(), nullable=True),
        sa.Column("filters", JSONColumn, nullable=True),
        sa.Column("source_dataset", sa.String(255), nullable=False),
        sa.Column("source_relation", sa.Text(), nullable=False),
        sa.Column("source_columns", JSONColumn, nullable=False),
        # NULL for a derived record. Never a reconstructed statement.
        sa.Column("query", sa.Text(), nullable=True),
        sa.Column("query_sequence", sa.Integer(), nullable=True),
        sa.Column("analysis_tool", sa.String(50), nullable=False),
        sa.Column("validation_status", sa.String(20), nullable=False),
        sa.Column("confidence", sa.String(10), nullable=True),
        sa.Column("node_id", sa.String(500), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("classification", sa.String(20), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("details", JSONColumn, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            _in_list("evidence_type", EvidenceType),
            name="ck_investigation_evidence_evidence_type_valid",
        ),
        sa.CheckConstraint(
            _in_list("validation_status", EvidenceValidationStatus),
            name="ck_investigation_evidence_validation_status_valid",
        ),
        sa.CheckConstraint(
            _in_list("confidence", EvidenceConfidence),
            name="ck_investigation_evidence_confidence_valid",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name="fk_investigation_evidence_investigation_id_investigations",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_investigation_evidence"),
    )
    op.create_index(
        "ix_investigation_evidence_investigation_id", "investigation_evidence", ["investigation_id"]
    )
    op.create_index(
        "ix_investigation_evidence_company_id", "investigation_evidence", ["company_id"]
    )
    op.create_index(
        "ix_investigation_evidence_investigation_type",
        "investigation_evidence",
        ["investigation_id", "evidence_type"],
    )
    op.create_index(
        "ix_investigation_evidence_investigation_sequence",
        "investigation_evidence",
        ["investigation_id", "sequence"],
    )

    op.create_table(
        "investigation_queries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("purpose", sa.String(40), nullable=False),
        sa.Column("sql", sa.Text(), nullable=False),
        # The count only. A bound parameter can be a customer name.
        sa.Column("parameter_count", sa.Integer(), nullable=False),
        sa.Column("rows_returned", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(10), nullable=False),
        sa.Column("error", sa.String(500), nullable=True),
        sa.Column("depth", sa.Integer(), nullable=True),
        sa.Column("node_id", sa.String(500), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            _in_list("status", QueryStatus), name="ck_investigation_queries_status_valid"
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name="fk_investigation_queries_investigation_id_investigations",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_investigation_queries"),
        # The sequence is the trace's identity, so a duplicate is a double-write.
        sa.UniqueConstraint(
            "investigation_id", "sequence", name="uq_investigation_queries_sequence"
        ),
    )
    op.create_index(
        "ix_investigation_queries_investigation_id", "investigation_queries", ["investigation_id"]
    )

    op.create_table(
        "investigation_audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investigation_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(40), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        # The reproducible field: a monotonic offset from the run's start.
        sa.Column("elapsed_ms", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", JSONColumn, nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.CheckConstraint(
            _in_list("event_type", AuditEventType),
            name="ck_investigation_audit_events_event_type_valid",
        ),
        sa.ForeignKeyConstraint(
            ["investigation_id"],
            ["investigations.id"],
            name="fk_investigation_audit_events_investigation_id_investigations",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_investigation_audit_events"),
    )
    op.create_index(
        "ix_investigation_audit_events_investigation_id",
        "investigation_audit_events",
        ["investigation_id"],
    )
    op.create_index(
        "ix_investigation_audit_events_sequence",
        "investigation_audit_events",
        ["investigation_id", "sequence"],
    )


def downgrade() -> None:
    op.drop_table("investigation_audit_events")
    op.drop_table("investigation_queries")
    op.drop_table("investigation_evidence")
    op.drop_table("investigations")
